# These settings can be accessed via {{ site.title }}, {{ site.email }}, in the html pages.
title: Michael Teter
email: blog@michaelteter.com
# art: My Generative Art
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michaelteter.com" # the base hostname & protocol for your site
github_username: michaelteter
linkedin_username: michaelteter

future: true

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

github: [metadata]

permalink: /archived-posts/:year/:month/:day/:title:output_ext

header_pages:
  - digital-art.md
  - resume.md # if you make one
